# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rule.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from common.commonGlobals import whoSelectItem, whereSelectItem, whichSelectItem, userVisibleSelectItem, buttonLabel, commonLabel, langField, errorCodeInputData, serverPhase, clientPhase
from initAction import initAction

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QListWidget, QVBoxLayout, QMessageBox, QDesktopWidget

phaseCombiComboBox = {}
whoComboBox = {}
whereComboBox = {}
whichComboBox = {}
userVisibleComboBox = {}

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, userName, password):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.listView = QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 35, 300, 640))
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(320, 10, 1010, 665))
        self.basictab = QtWidgets.QWidget()

        self.errCodeLabel = QtWidgets.QLabel(self.basictab)
        self.errCodeLabel.setGeometry(QtCore.QRect(0, 0, 200, 20))
        self.errCodeLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errCodeLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.whoLabel = QtWidgets.QLabel(self.basictab)
        self.whoLabel.setGeometry(QtCore.QRect(0, 25, 200, 20))
        self.whoLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whoLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.whereLabel = QtWidgets.QLabel(self.basictab)
        self.whereLabel.setGeometry(QtCore.QRect(0, 50, 200, 20))
        self.whereLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whereLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.whichLabel = QtWidgets.QLabel(self.basictab)
        self.whichLabel.setGeometry(QtCore.QRect(0, 75, 200, 20))
        self.whichLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whichLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.whatLabel = QtWidgets.QLabel(self.basictab)
        self.whatLabel.setGeometry(QtCore.QRect(0, 100, 200, 20))
        self.whatLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whatLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.userVisibleLabel = QtWidgets.QLabel(self.basictab)
        self.userVisibleLabel.setGeometry(QtCore.QRect(0, 125, 200, 20))
        self.userVisibleLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.userVisibleLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.phaseLabel = QtWidgets.QLabel(self.basictab)
        self.phaseLabel.setGeometry(QtCore.QRect(0, 150, 200, 20))
        self.phaseLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phaseLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.nameLabel = QtWidgets.QLabel(self.basictab)
        self.nameLabel.setGeometry(QtCore.QRect(0, 175, 200, 20))
        self.nameLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        '''self.producerLabel = QtWidgets.QLabel(self.basictab)
        self.producerLabel.setGeometry(QtCore.QRect(0, 200, 200, 20))
        self.producerLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.producerLabel.setFrameShadow(QtWidgets.QFrame.Sunken)'''

        self.descLabel = QtWidgets.QLabel(self.basictab)
        self.descLabel.setGeometry(QtCore.QRect(0, 200, 200, 20))
        self.descLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.createByLabel = QtWidgets.QLabel(self.basictab)
        self.createByLabel.setGeometry(QtCore.QRect(0, 380, 200, 20))
        self.createByLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createByLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.errMessageLabel = QtWidgets.QLabel(self.basictab)
        self.errMessageLabel.setGeometry(QtCore.QRect(0, 405, 200, 20))
        self.errMessageLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errMessageLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.approvalByLabel = QtWidgets.QLabel(self.basictab)
        self.approvalByLabel.setGeometry(QtCore.QRect(0, 585, 200, 20))
        self.approvalByLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.approvalByLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.approvalLabel = QtWidgets.QLabel(self.basictab)
        self.approvalLabel.setGeometry(QtCore.QRect(0, 610, 200, 20))
        self.approvalLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.approvalLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        #Input Field
        self.searchListField = QtWidgets.QLineEdit(self.centralwidget)
        self.searchListField.setGeometry(QtCore.QRect(10, 10, 300, 20))
        self.searchListField.setObjectName(errorCodeInputData.ERR_PRODUCER.value.FIELD.value)
        self.searchListField.setPlaceholderText("Search by Error Code")

        self.errCodeField = QtWidgets.QLabel(self.basictab)
        self.errCodeField.setGeometry(QtCore.QRect(200, 0, 400, 20))
        self.errCodeField.setObjectName(errorCodeInputData.ERR_CODE.value.FIELD.value)

        self.whoField = QtWidgets.QComboBox(self.basictab)
        for i in whoSelectItem:
            self.whoField.addItem(i.values[1])
        self.whoField.setGeometry(QtCore.QRect(200, 25, 400, 20))
        self.whoField.setObjectName(errorCodeInputData.ERR_WHO.value.FIELD.value)

        self.whereField = QtWidgets.QComboBox(self.basictab)
        for i in whereSelectItem:
            self.whereField.addItem(i.values[1])
        self.whereField.setGeometry(QtCore.QRect(200, 50, 400, 20))
        self.whereField.setObjectName(errorCodeInputData.ERR_WHERE.value.FIELD.value)

        self.whichField = QtWidgets.QComboBox(self.basictab)
        for i in whichSelectItem:
            self.whichField.addItem(i.values[1])
        self.whichField.setGeometry(QtCore.QRect(200, 75, 400, 20))
        self.whichField.setObjectName(errorCodeInputData.ERR_WHICH.value.FIELD.value)

        self.whatField = QtWidgets.QLineEdit(self.basictab)
        self.whatField.setGeometry(QtCore.QRect(200, 100, 400, 20))
        self.whatField.setObjectName(errorCodeInputData.ERR_WHAT.value.FIELD.value)
        self.whatField.setEnabled(False)

        self.userVisibleField = QtWidgets.QComboBox(self.basictab)
        for i in userVisibleSelectItem:
            self.userVisibleField.addItem(i.values[1])
        self.userVisibleField.setGeometry(QtCore.QRect(200, 125, 400, 20))
        self.userVisibleField.setObjectName(errorCodeInputData.ERR_USER_VISIBLE.value.FIELD.value)

        self.phaseField = QtWidgets.QComboBox(self.basictab)
        for phase in serverPhase:
            for subPhase in phase.values[2]:
                self.phaseField.addItem(phase.values[1]+" - "+subPhase.values[1])
        for phase in clientPhase:
            for subPhase in phase.values[2]:
                self.phaseField.addItem(phase.values[1]+" - "+subPhase.values[1])
        self.phaseField.setGeometry(QtCore.QRect(200, 150, 400, 20))
        self.phaseField.setObjectName(errorCodeInputData.ERR_PHASE.value.FIELD.value)

        self.nameField = QtWidgets.QLineEdit(self.basictab)
        self.nameField.setGeometry(QtCore.QRect(200, 175, 400, 20))
        self.nameField.setObjectName(errorCodeInputData.ERR_PRODUCER.value.FIELD.value)

        '''self.producerField = QtWidgets.QLineEdit(self.basictab)
        self.producerField.setGeometry(QtCore.QRect(200, 200, 400, 20))
        self.producerField.setObjectName(errorCodeInputData.ERR_PRODUCER.value.FIELD.value)'''

        self.descEnLabel = QtWidgets.QLabel(self.basictab)
        self.descEnLabel.setGeometry(QtCore.QRect(200, 200, 200, 20))
        self.descEnLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descEnLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.descEnField = QtWidgets.QTextEdit(self.basictab)
        self.descEnField.setGeometry(QtCore.QRect(200, 225, 800, 60))
        self.descEnField.setObjectName(errorCodeInputData.ERR_DESC_MESSAGE.value.FIELD.value+"_"+langField.EN.value)
        self.descEnField.setTabChangesFocus(True)

        self.descCnLabel = QtWidgets.QLabel(self.basictab)
        self.descCnLabel.setGeometry(QtCore.QRect(200, 290, 200, 20))
        self.descCnLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descCnLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.descCnField = QtWidgets.QTextEdit(self.basictab)
        self.descCnField.setGeometry(QtCore.QRect(200, 315, 800, 60))
        self.descCnField.setObjectName(errorCodeInputData.ERR_DESC_MESSAGE.value.FIELD.value+"_"+langField.CN.value)
        self.descCnField.setTabChangesFocus(True)

        self.createByField = QtWidgets.QLineEdit(self.basictab)
        self.createByField.setGeometry(QtCore.QRect(200, 380, 400, 20))
        self.createByField.setObjectName(errorCodeInputData.ERR_CREATE.value.FIELD.value)
        self.createByField.setEnabled(False)

        self.errMessageEnLabel = QtWidgets.QLabel(self.basictab)
        self.errMessageEnLabel.setGeometry(QtCore.QRect(200, 405, 200, 20))
        self.errMessageEnLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errMessageEnLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.errMessageEnField = QtWidgets.QTextEdit(self.basictab)
        self.errMessageEnField.setGeometry(QtCore.QRect(200, 430, 800, 60))
        self.errMessageEnField.setObjectName(errorCodeInputData.ERR_MESSAGE.value.FIELD.value+"_"+langField.EN.value)
        self.errMessageEnField.setTabChangesFocus(True)

        self.errMessageCnLabel = QtWidgets.QLabel(self.basictab)
        self.errMessageCnLabel.setGeometry(QtCore.QRect(200, 495, 200, 20))
        self.errMessageCnLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errMessageCnLabel.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.errMessageCnField = QtWidgets.QTextEdit(self.basictab)
        self.errMessageCnField.setGeometry(QtCore.QRect(200, 525, 800, 60))
        self.errMessageCnField.setObjectName(errorCodeInputData.ERR_MESSAGE.value.FIELD.value+"_"+langField.CN.value)
        self.errMessageCnField.setTabChangesFocus(True)

        self.approvalByField = QtWidgets.QLineEdit(self.basictab)
        self.approvalByField.setGeometry(QtCore.QRect(200, 585, 400, 20))
        self.approvalByField.setObjectName(errorCodeInputData.ERR_APPROVAL.value.FIELD.value)
        self.approvalByField.setEnabled(False)

        self.approvalYesField = QtWidgets.QRadioButton(self.basictab)
        self.approvalYesField.setGeometry(QtCore.QRect(220, 610, 200, 20))
        #self.approvalYesField.setObjectName(errorCodeInputData.ERR_APPROVAL.value.FIELD.value)
        self.approvalYesField.approval = True

        self.approvalNoField = QtWidgets.QRadioButton(self.basictab)
        self.approvalNoField.setGeometry(QtCore.QRect(400, 610, 200, 20))
        #self.approvalNoField.setObjectName(errorCodeInputData.ERR_APPROVAL.value.FIELD.value)
        self.approvalNoField.approval = False

        self.tabWidget.addTab(self.basictab, "")
        self.examplestab = QtWidgets.QWidget()

        self.loadOriButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadOriButton.setGeometry(QtCore.QRect(10, 680, 300, 15))
        #self.loadOriButton.setEnabled(False)

        self.loadJsonButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadJsonButton.setGeometry(QtCore.QRect(10, 695, 300, 15))
        #self.loadJsonButton.setEnabled(False)

        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(320, 680, 100, 30))

        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(420, 680, 100, 30))

        self.outputButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputButton.setGeometry(QtCore.QRect(620, 680, 100, 30))

        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(520, 680, 100, 30))

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.buttonEvent(MainWindow, userName, password)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def buttonEvent(self, MainWindow, userName, password):
        print("buttonEvent")
        self.addButton.clicked.connect(lambda: initAction.addToList(self, userName))
        self.saveButton.clicked.connect(lambda: initAction.saveAction(self))
        self.loadOriButton.clicked.connect(lambda: initAction.loadExcelJson(self.listView))
        self.loadJsonButton.clicked.connect(lambda: initAction.loadFromMinio(self.listView))
        self.outputButton.clicked.connect(lambda: initAction.outputJson(self, initAction, userName, password))
        self.deleteButton.clicked.connect(lambda: initAction.deleteAction(self))
        self.listView.itemClicked.connect(self.selectItem)

        self.searchListField.textChanged.connect(lambda: initAction.text_search(self.listView, text=self.searchListField.text()))

        self.whoField.currentTextChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_WHO.value.FIELD.value, subField=None, comboBox=whoComboBox, text=self.whoField.currentIndex()))
        self.whereField.currentTextChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_WHERE.value.FIELD.value, subField=None, comboBox=whereComboBox, text=self.whereField.currentIndex()))
        self.whichField.currentTextChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_WHICH.value.FIELD.value, subField=None, comboBox=whichComboBox, text=self.whichField.currentIndex()))
        self.userVisibleField.currentTextChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_USER_VISIBLE.value.FIELD.value, subField=None, comboBox=userVisibleComboBox, text=self.userVisibleField.currentIndex()))
        self.phaseField.currentTextChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_PHASE.value.FIELD.value, subField=None, comboBox=phaseCombiComboBox, text=self.phaseField.currentIndex()))
        self.nameField.textChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_NAME.value.FIELD.value, subField=None, comboBox=None, text=self.nameField.text()))
        self.descEnField.textChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_DESC_MESSAGE.value.FIELD.value, subField=langField.EN.value, comboBox=None, text=self.descEnField.toPlainText()))
        self.descCnField.textChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_DESC_MESSAGE.value.FIELD.value, subField=langField.CN.value, comboBox=None, text=self.descCnField.toPlainText()))
        self.errMessageEnField.textChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_MESSAGE.value.FIELD.value, subField=langField.EN.value, comboBox=None, text=self.errMessageEnField.toPlainText()))
        self.errMessageCnField.textChanged.connect(lambda: initAction.text_change(self.listView, errorCodeInputData.ERR_MESSAGE.value.FIELD.value, subField=langField.CN.value, comboBox=None, text=self.errMessageCnField.toPlainText()))
        self.approvalYesField.toggled.connect(lambda: initAction.onClickedApproval(self, MainWindow, True, userName))
        self.approvalNoField.toggled.connect(lambda: initAction.onClickedApproval(self, MainWindow, False, userName))

    def popMessage(self, message, status):
        print("popMessage")
        popupMessage = QMessageBox()
        popupMessage.setWindowTitle("Message")
        popupMessage.setText(message)
        popupMessage.setIcon(status)
        popupMessage.exec_()

    def selectItem(self):
        self.showView(initAction.selectListView(self.listView))

    def setBlockSignals(self, bool):
        self.errCodeField.blockSignals(bool)
        self.whoField.blockSignals(bool)
        self.whereField.blockSignals(bool)
        self.whichField.blockSignals(bool)
        self.whatField.blockSignals(bool)
        self.userVisibleField.blockSignals(bool)
        self.nameField.blockSignals(bool)
        self.phaseField.blockSignals(bool)
        self.descEnField.blockSignals(bool)
        self.descCnField.blockSignals(bool)
        self.errMessageEnField.blockSignals(bool)
        self.errMessageCnField.blockSignals(bool)
        self.approvalYesField.blockSignals(bool)
        self.approvalNoField.blockSignals(bool)

    def findIndexOfComboBox(self, selectItem, dataValue, comboBox):
        index = comboBox.get(selectItem.getErrData(dataValue.FIELD.value))
        return index if not index is None else -1

    def showView(self, selectItem):
        print("showView")
        self.setBlockSignals(True)
        self.errCodeField.setText(" " + str(selectItem.getErrData(errorCodeInputData.ERR_CODE.value.FIELD.value)))

        self.whoField.setCurrentIndex(
            self.findIndexOfComboBox(selectItem, errorCodeInputData.ERR_WHO.value, whoComboBox)
        )
        self.whereField.setCurrentIndex(
            self.findIndexOfComboBox(selectItem, errorCodeInputData.ERR_WHERE.value, whereComboBox)
        )
        self.whichField.setCurrentIndex(
            self.findIndexOfComboBox(selectItem, errorCodeInputData.ERR_WHICH.value, whichComboBox)
        )
        self.whatField.setText(str(selectItem.getErrData(errorCodeInputData.ERR_WHAT.value.FIELD.value)))
        self.userVisibleField.setCurrentIndex(
            self.findIndexOfComboBox(selectItem, errorCodeInputData.ERR_USER_VISIBLE.value, userVisibleComboBox)
        )
        self.phaseField.setCurrentIndex(
            self.findIndexOfComboBox(selectItem, errorCodeInputData.ERR_PHASE.value, phaseCombiComboBox)
        )
        self.nameField.setText(str(selectItem.getErrData(errorCodeInputData.ERR_NAME.value.FIELD.value)))
        self.descEnField.setPlainText(str(selectItem.getErrSubData(errorCodeInputData.ERR_DESC_MESSAGE.value.FIELD.value, langField.EN.value)))
        self.descCnField.setPlainText(str(selectItem.getErrSubData(errorCodeInputData.ERR_DESC_MESSAGE.value.FIELD.value, langField.CN.value)))
        self.createByField.setText(str(selectItem.getErrData(errorCodeInputData.ERR_CREATE.value.FIELD.value)))
        self.errMessageEnField.setPlainText(str(selectItem.getErrSubData(errorCodeInputData.ERR_MESSAGE.value.FIELD.value, langField.EN.value)))
        self.errMessageCnField.setPlainText(str(selectItem.getErrSubData(errorCodeInputData.ERR_MESSAGE.value.FIELD.value, langField.CN.value)))
        self.approvalByField.setText(str(selectItem.getErrData(errorCodeInputData.ERR_APPROVAL_BY.value.FIELD.value)))

        if selectItem.getErrData(errorCodeInputData.ERR_APPROVAL.value.FIELD.value)=="True":
            self.approvalYesField.setChecked(True)
        else:
            self.approvalNoField.setChecked(True)
        self.setBlockSignals(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Error Code Generation Tools"))

        self.errCodeLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_CODE.value.LABEL.value))
        self.whoLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_WHO.value.LABEL.value))
        self.whereLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_WHERE.value.LABEL.value))
        self.whichLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_WHICH.value.LABEL.value))
        self.whatLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_WHAT.value.LABEL.value))
        self.userVisibleLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_USER_VISIBLE.value.LABEL.value))
        self.nameLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_NAME.value.LABEL.value))
        self.phaseLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_PHASE.value.LABEL.value))
        self.descLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_DESC_MESSAGE.value.LABEL.value))
        self.descEnLabel.setText(_translate("MainWindow", commonLabel.EN.value))
        self.descCnLabel.setText(_translate("MainWindow", commonLabel.CN.value))
        self.createByLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_CREATE.value.LABEL.value))
        self.errMessageLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_MESSAGE.value.LABEL.value))
        self.errMessageEnLabel.setText(_translate("MainWindow", commonLabel.EN.value))
        self.errMessageCnLabel.setText(_translate("MainWindow", commonLabel.CN.value))
        self.approvalByLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_APPROVAL_BY.value.LABEL.value))
        self.approvalLabel.setText(_translate("MainWindow", errorCodeInputData.ERR_APPROVAL.value.LABEL.value))
        self.approvalYesField.setText(_translate("MainWindow", "Yes"))
        self.approvalNoField.setText(_translate("MainWindow", "No"))

        self.approvalgroup = QtWidgets.QButtonGroup()
        self.approvalgroup.addButton(self.approvalYesField)
        self.approvalgroup.addButton(self.approvalNoField)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basictab), _translate("MainWindow", "Basic Info"))

        self.addButton.setText(_translate("MainWindow", buttonLabel.ADD.value))
        self.saveButton.setText(_translate("MainWindow", buttonLabel.SAVE.value))
        self.deleteButton.setText(_translate("MainWindow", buttonLabel.DELETE.value))
        self.loadOriButton.setText(_translate("MainWindow", buttonLabel.LOAD_ORI_JSON.value))
        self.loadJsonButton.setText(_translate("MainWindow", buttonLabel.LOAD_JSON.value))
        self.outputButton.setText(_translate("MainWindow", buttonLabel.OUTPUT_JSON.value))

    def initCombox(self):
        self.definePhaseCombox((serverPhase, clientPhase))
        self.defineCombox(whoComboBox, whoSelectItem)
        self.defineCombox(whereComboBox, whereSelectItem)
        self.defineCombox(whichComboBox, whichSelectItem)
        self.defineCombox(userVisibleComboBox, userVisibleSelectItem)

    def defineCombox(self, listBox, listSrc):
        print("defineCombox")
        count = 0
        for item in listSrc:
            listBox[str(item.values[0])] = count
            count+=1

    def definePhaseCombox(self, ListPhase):
        print("defineCombinCombox")
        count = 0
        for item in ListPhase:
            for phase in item:
                for subPhase in phase.values[2]:
                    phaseCombiComboBox[str(phase.values[0]) + str(subPhase.values[0])] = count
                    count+=1

    def autoLoad(self):
        initAction.loadJson(self.listView)
        self.initCombox()
        self.whoField.setCurrentIndex(-1)
        self.whereField.setCurrentIndex(-1)
        self.whichField.setCurrentIndex(-1)
        self.userVisibleField.setCurrentIndex(-1)
        self.phaseField.setCurrentIndex(-1)

    def setCenter(self, MainWindow):
        screen = QDesktopWidget().screenGeometry()
        size = MainWindow.geometry()
        newL = (screen.width() - size.width()) / 2
        newT = (screen.height() - size.height()) /2
        MainWindow.move(int(newL), int(newT))

    def main(self, MainWindow, userName, password):
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow, userName, password)
        ui.autoLoad()
        ui.setCenter(MainWindow)
        MainWindow.show()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())